config/routes.rb
Rails.application.routes.draw do
  resources :approve_mechanics, only: [:index, :update, :destroy]
  resources :mechanic_profiles
  resources :mechanic_searches
  resources :inspections
  resources :mechanics do
    resources :inspections
  end
  root to: 'visitors#index'
  devise_for :users
  resources :users, except: [:new, :create]

  get 'users/:id/set_admin' => 'users#set_admin'

  resources :models, only: :index
end

app/controllers/approve_mechanics_controller.rb
class ApproveMechanicsController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_admin!

  before_action :set_mechanic, except: :index

  def index
    @approved_mechanics = Mechanic.approved
    @unapproved_mechanics = Mechanic.unapproved
  end

  def update
    @mechanic.update(approved: true)
    if @mechanic.save
      redirect_to action: :index
    else
      render :index, error: @mechanic.errors
    end
  end

  def destroy
    @mechanic.update(approved: false)
    if @mechanic.save
      redirect_to action: :index
    else
      render :index, error: @mechanic.errors
    end
  end

  private

  def set_mechanic
    @mechanic = Mechanic.find(params[:id])
  end
end

app/views/approve_mechanics/index.html.haml
%body.app-page
  = render 'layouts/app_navigation'
.container
  .row
    %h3 Approve Mechanics
    %table.table.table-striped
      %tbody
        %tr
          %th Mechanic Email
          %th Approve
        - @unapproved_mechanics.each do |mechanic|
          %tr
            %td= link_to mechanic.user.email, mechanic_path(mechanic)
            %td= link_to 'Approve', approve_mechanic_path(mechanic), method: :put
  .row
    %h3 Unapprove Mechanics
    %table.table.table-striped
      %tbody
        %tr
          %th Mechanic Email
          %th Unapprove
        - @approved_mechanics.each do |mechanic|
          %tr
            %td= link_to mechanic.user.email, mechanic_path(mechanic)
            %td= link_to 'Unapprove', "approve_mechanics/#{mechanic.id}", method: :delete