config/routes.rb
Rails.application.routes.draw do
  resources :approve_mechanics, only: [:index, :update, :destroy]
  resources :mechanic_profiles
  resources :mechanic_searches
  resources :inspections
  resources :mechanics do
    resources :inspections
  end
  root to: 'visitors#index'
  devise_for :users
  resources :users, except: [:new, :create]

  get 'users/:id/set_admin' => 'users#set_admin'

  resources :models, only: :index
end

app/models/inspection.rb
class Inspection < ActiveRecord::Base
  belongs_to :user
  belongs_to :mechanic

  attr_accessor :card_number, :card_year, :card_month, :card_cvv

  validates :user_id, presence: true
  validates :mechanic_id, presence: true
  # validates :location, presence: true
  validates :vehicle_year, presence: true
  validates :vehicle_make, presence: true
  validates :vehicle_model, presence: true
  validates :your_name, presence: true
  validates :your_address, presence: true
  validates :your_phone, presence: true
  validates :your_email, presence: true, email: true
  validates :seller_name, presence: true
  validates :seller_address, presence: true
  validates :seller_phone, presence: true
  validates :seller_email, presence: true, email: true
  validates :card_number, presence: true, credit_card_number: true
  validates :card_year, presence: true, numericality: true, length: { is: 4 }
  validates :card_month, presence: true, numericality: true, length: { is: 2 }
  validates :card_cvv, presence: true, numericality: true, length: { minimum: 3, maximum: 4 }

  after_validation :set_card_number_errors
  after_create :send_letter

  def corrected_time
    time.change(year: date.year, month: date.month, day: date.day)
  end

  private

  def send_letter
    InspectionMailer.send_inspection_to_user(self).deliver
    InspectionMailer.send_inspection_to_admin(self).deliver
  end

  handle_asynchronously :send_letter

  def set_card_number_errors
    errors.add(:card_number, "Card year #{errors[:card_year].first}") if errors[:card_year].any?
    errors.add(:card_number, "Card month #{errors[:card_month].first}") if errors[:card_month].any?
    errors.add(:card_number, "CVV #{errors[:card_cvv].first}") if errors[:card_cvv].any?
  end
end

app/controllers/inspections_controller.rb
class InspectionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_inspection, only: [:show, :edit, :update, :destroy]
  before_action :set_mechanic, only: [:new, :create]

  # GET /inspections
  # GET /inspections.json
  def index
    @inspections = Inspection.where(user_id: current_user.andand.id)
  end

  # GET /inspections/1
  # GET /inspections/1.json
  def show
    @inspections = Inspection.find(params[:id])
  end

  # GET /inspections/new
  def new
    @inspection = Inspection.new
  end

  # GET /inspections/1/edit
  def edit
  end

  # POST /inspections
  # POST /inspections.json
  def create
    @inspection = current_user.inspections.new(inspection_params)
    @inspection.time = @inspection.corrected_time
    @inspection.mechanic = @mechanic

    respond_to do |format|
      if @inspection.valid?
        @btransaction = Braintree::Transaction.sale(amount: @inspection.mechanic.price,
                                                    credit_card: { number: inspection_params[:card_number],
                                                                   expiration_year: inspection_params[:card_year],
                                                                   expiration_month: inspection_params[:card_month],
                                                                   cvv: inspection_params[:cvv] },
                                                    customer: { first_name: inspection_params[:your_name],
                                                                email: inspection_params[:your_email] },
                                                    billing: { street_address: inspection_params[:your_address] },
                                                    options: { submit_for_settlement: true })
        if @btransaction.success?
            @inspection.braintree_id = @btransaction.transaction.id
            @inspection.save
            format.html { redirect_to @inspection, notice: 'Inspection was successfully scheduled.' }
            format.json { render :show, status: :created, location: @inspection }
        else
          @inspection.errors.add(:card_number, @btransaction.errors.map(&:message).join(".\n"))
          format.html { render :new }
          format.json { render json: @inspection.errors, status: :unprocessable_entity }
        end
      else
        format.html { render :new }
        format.json { render json: @inspection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inspections/1
  # PATCH/PUT /inspections/1.json
  def update
    respond_to do |format|
      if @inspection.update(inspection_params)
        format.html { redirect_to @inspection, notice: 'Inspection was successfully updated.' }
        format.json { render :show, status: :ok, location: @inspection }
      else
        format.html { render :edit }
        format.json { render json: @inspection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inspections/1
  # DELETE /inspections/1.json
  def destroy
    @inspection.destroy
    respond_to do |format|
      format.html { redirect_to inspections_url, notice: 'Inspection was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_mechanic
      @mechanic   = Mechanic.find_by_id(params[:mechanic_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_inspection
      @inspection = Inspection.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inspection_params
      params.require(:inspection).permit(:mechanic_id,
        :user_id, :location, :vehicle_year,
        :vehicle_make, :vehicle_model, :date, :time, :created_at, :updated_at,
        :your_name, :your_address, :your_phone, :your_email,
        :seller_name, :seller_address, :seller_phone, :seller_email, :mechanic_id, :user_id,
        :card_number, :card_year, :card_month, :card_cvv)
    end
end

app/helpers/inspections_helper.rb
module InspectionsHelper
end

app/views/inspections/_form.html.haml
= render 'layouts/app_navigation'
%section
  .container
    = simple_form_for [@mechanic, @inspection] do |f|
      .row
        .col-md-12
          = f.error_notification
      .row
        .col-md-12
          %h3.text-left Mechanic Info
          .col-md-3
            %h4
              = 'NAME:'
              = @mechanic.andand.user.andand.name
          .col-md-3
            %h4
              = 'SPECIALITY:'
              = @mechanic.speciality
          .col-md-3
            %h4
              = 'ZIP:'
              = @mechanic.zip
          .col-md-3
            %h4
              = 'PRICE:'
              $#{@mechanic.price}
      .row
        .col-md-6
          %h3.text-left Buyer Info
          .form-inputs
            = f.input :your_name
            = f.input :your_address
            = f.input :your_phone
            = f.input :your_email
        .col-md-6
          %h3.text-left Vehicle Info
          .form-inputs
            %span Vehicle Year
            = f.input :vehicle_year,  as: :select_picker, collection: [*1960..2016]
            %span Vehicle Make
            = f.input :vehicle_make,  as: :select_picker, collection: Edmunds::Make.new.find_all.map { |user| user['name'] }
            %span Vehicle Model
            - vehicle_models = []
            - Edmunds::Make.new.find_all.map do |auto|
              - auto['models'].map do |model|
                - vehicle_models << model['name']
            = f.input :vehicle_model, as: :select_picker, collection: vehicle_models
      .row
        .col-md-6
          %h3.text-left Inspection Info
          .form-inputs
            = f.input :seller_name
            = f.input :seller_address
            = f.input :seller_phone
            = f.input :seller_email
            -# = f.input :location
            = f.input :date
            = f.input :time
        .col-md-6
          %h3.text-left Payment
          .form-inputs
            = f.input :card_number, label: 'Card Number', input_html: { placeholder: 'Card Number' }
            = f.input :card_cvv, as: :password, label: 'CVV Number', input_html: { placeholder: 'CVV' }
            = f.input :card_month,  as: :select, collection: [*1..12].map { |n| n.to_s.rjust(2, '0') }, prompt: 'Month'
            = f.input :card_year,  as: :select, collection: [*Date.today.year..Date.today.year + 7], prompt: 'Year'

            .form-actions
              = f.button :submit, 'Charge'
              Your card will be charged for the listed mechanic inspection price.

app/views/inspections/edit.html.haml
%h1 Editing Inspection
= render 'form'
= link_to 'Show', @inspection
|
= link_to 'Back', inspections_path

app/views/inspections/index.html.haml
%p#notice= notice
%h1 Listing Inspections
%table
  %thead
    %tr
      %th Mechanic
      %th User
      %th Location
      %th Vehicle year
      %th Vehicle make
      %th Vehicle model
      %th Date
      %th Time
      %th Created at
      %th Updated at
      %th{colspan: "3"}
  %tbody
    - @inspections.each do |inspection|
      %tr
        %td= inspection.mechanic_id
        %td= inspection.user_id
        %td= inspection.location
        %td= inspection.vehicle_year
        %td= inspection.vehicle_make
        %td= inspection.vehicle_model
        %td= inspection.date
        %td= inspection.time
        %td= inspection.created_at
        %td= inspection.updated_at
        %td= link_to 'Show', inspection
        %td= link_to 'Edit', edit_inspection_path(inspection)
        %td= link_to 'Destroy', inspection, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Inspection', new_inspection_path

app/views/inspections/new.html.haml
%body.app-page
= render 'layouts/app_navigation'
.container
  %h1 Schedule Inspection
  = render 'form'
= render 'layouts/footer'

app/views/inspections/show.html.haml
%body.app-page
= render 'layouts/app_navigation'
.container
  %p
    %strong Mechanic:
    = Mechanic.find(@inspection.mechanic_id).user.andand.name
  %p
    %strong Customer:
    = @inspection.your_name
  -# %p
  -#   %strong Location:
  -#   = @inspection.location
  %p
    %strong Vehicle year:
    = @inspection.vehicle_year
  %p
    %strong Vehicle make:
    = @inspection.vehicle_make
  %p
    %strong Vehicle model:
    = @inspection.vehicle_model
  %p
    %strong Date:
    = @inspection.date
  %p
    %strong Time:
    = @inspection.time
  %p
    %strong Created at:
    = @inspection.created_at
  %p
    %strong Updated at:
    = @inspection.updated_at
  = link_to 'Edit', edit_inspection_path(@inspection)
  |
  = link_to 'Back', inspections_path
= render 'layouts/footer'

:javascript
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-87624294-3', 'auto');
  ga('send', 'pageview');