config/routes.rb
Rails.application.routes.draw do
  resources :approve_mechanics, only: [:index, :update, :destroy]
  resources :mechanic_profiles
  resources :mechanic_searches
  resources :inspections
  resources :mechanics do
    resources :inspections
  end
  root to: 'visitors#index'
  devise_for :users
  resources :users, except: [:new, :create]

  get 'users/:id/set_admin' => 'users#set_admin'

  resources :models, only: :index
end

app/views/layouts/_app_navigation.html.haml
%nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", type: "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'
        = render 'layouts/nav_links_for_auth'

app/views/layouts/_footer.html.haml
/ Page Footer Start
%footer.page-footer
  .container.text-center
    / Social links
    .social-links
      %a{href: "#", target: "_blank", title: "Facebook"}
        %i.fa.fa-facebook
      %a{href: "#", target: "_blank", title: "Twitter"}
        %i.fa.fa-twitter
      %a{href: "#", target: "_blank", title: "Behance"}
        %i.fa.fa-behance
      %a{href: "#", target: "_blank", title: "Linkedin"}
        %i.fa.fa-linkedin
      %a{href: "#", target: "_blank", title: "Pinterst"}
        %i.fa.fa-pinterest
    .copy-right.mt-50
      %a.alt-font{href: "#"} © InspectX 2015
      %p= link_to 'Terms of Use', page_path('terms')
  %a.scroll.scroll-to-top{href: "#top"}
    %i.fa.fa-angle-up
/ Page footer end

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{class: "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", type: "button"} ×
      = content_tag :div, msg, id: "flash_#{name}"

app/views/layouts/_nav_links_for_auth.html.haml
- if user_signed_in?
  - if current_user.try(:admin?)
    %li= link_to 'Manage Users', users_path
    %li= link_to 'Manage Mechanics', approve_mechanics_path
  - if current_user.try(:mechanic?)
    %li= link_to 'Edit Mechanic Info', edit_mechanic_path(current_user.try(:mechanic))
  %li= link_to 'Edit account', edit_user_registration_path
  %li= link_to 'Sign out', destroy_user_session_path, :method=>'delete'
- else
  %li= link_to 'Sign in', new_user_session_path , class: "btn  btn-user"
  %li= link_to 'Sign up', new_user_registration_path , class: "btn  btn-user"

app/views/layouts/_navigation.html.haml
/ Navigation panel
%nav.main-nav.white.transparent.stick-fixed.js-transparent
  .full-wrapper.relative.clearfix
    / Logo
    .nav-logo-wrap
      %a.logo{href: "/"} INSPECTX
    .navbar-mobile
      %i.fa.fa-bars
    / Main Menu
    .inner-nav.navbar-desktop
      %ul.clearlist.scroll.scroll-nav{style: "max-height:806px;"}
        %li.active
          %a{href: "#home"} Home
        / End Item With Sub
        %li
          %a{href: "#about"} About
        %li
          %a{href: "#howitworks"} How It Works
        %li
          %a{href: "/mechanics/"} Find A Mechanic
        %li
          %a{href: "#contacts"} Contacts
        %li
          %a  
        / <li><a href="#"><i class="fa fa-phone"></i> 12-233-325-515</a></li>
        %li= render 'layouts/nav_links_for_auth'

app/views/layouts/_navigation_links.html.haml
%li= link_to 'About', page_path('about')

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}
    %meta{content: "mEfD8_uGkDpaSxzo9PQHqtQQI4tWl5jk5DE4bhGPNEc", name: "google-site-verification"}
    %title= content_for?(:title) ? yield(:title) : "inspectX - Pre-Purchase Inspections. Re-Invented."
    %meta{content: "#{content_for?(:description) ? yield(:description) : "inspectX"}", name: "description"}
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    = render 'layouts/messages'
    = yield